[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.3"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.97"
tokio = { version = "1.28", features = ["full"] }
rabe = "0.4.0"
thiserror = "1.0"
proc-macro2 = "1.0"
