[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.3"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.97"
tokio = { version = "1.28", features = ["full"] }
rabe = "0.4.0"
simplelog = "0.11.0"
log = "0.4.14"
sha2 = "0.10.2"